version: '3.3'
services:
  database:
    image: postgres
    container_name: portfoliogest-database-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfoliogest
      TZ: America/Recife
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - network-myproject
  node:
    image: 'node:16.13-alpine3.15'
    container_name: portfoliogest-api-container
    working_dir: /usr/src/api
    environment:
      - NODE_ENV=developmnent
      - TZ=America/Recife
    volumes:
      - ./:/usr/src/api
      - exclude:/usr/src/api/node_modules
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 768M
        reservations:
          memory: 400M
    networks:
      - network-myproject
    ports:
      - '8443:8443'
    command: sh -c 'npm install && npm run start:dev'
    restart: always
    depends_on:
      - database
volumes:
  db-data-myproject:
  exclude:
networks:
  network-myproject:
    driver: bridge